name: 📘 Update Docs

on:
  push:
    branches: [ "ISSUE-113" ]

permissions: read-all

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Update Docs
      env:
        TEST: ${{ secrets.ENV_SECRET }} 
      run: |
        python .github/run.py
