name: 📘 Update Docs

on:
  push:
    branches: [ "ISSUE-113" ]

permissions: read-all

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install mkdocs mkdocs-material
    - name: Update Docs
      run: |
        python .github/run.py
